language: ruby

rvm:
  - 1.9.3
  - 2.0.0

script:
  - bundle exec rake chef:spec

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#linyows"
